import type { Metadata } from 'next'
import { headers } from 'next/headers'
import { getLangDir } from 'rtl-detect'
import { notFound } from 'next/navigation'
import { hasLocale, NextIntlClientProvider } from 'next-intl'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter'
import { routing } from '@/i18n/routing'
import '../globals.css'
import { ProgressbarProvider } from '@/components/layout/progressbar-provider'
import { MuiThemeProvider } from '@/setup/theme/mui/mui'
import { LayoutClient } from '@/components/layout/layout.client'
import { fontsClassName } from './fonts/fonts'
import { QueryProvider } from '@/setup/api/query-client-provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode
  params: Promise<{ locale: string }>
}>) {
  const { locale } = await params

  if (!hasLocale(routing.locales, locale)) {
    notFound()
  }

  const userAgent = (await headers()).get('user-agent')

  const direction = getLangDir(locale)

  return (
    <html lang="en">
      <body dir={direction} className={fontsClassName}>
        <NextIntlClientProvider>
          <QueryProvider>
            <AppRouterCacheProvider>
              <MuiThemeProvider>
                <ProgressbarProvider>
                  <LayoutClient userAgent={userAgent || ''}>
                    {children}
                  </LayoutClient>
                </ProgressbarProvider>
              </MuiThemeProvider>
            </AppRouterCacheProvider>
          </QueryProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
